services:
    backend:
        image: backend-image
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=postgres
        container_name: backend
        depends_on:
          - db
          - redis
    
    frontend:
        image: frontend-image
        ports:
            - 5000:5000
        container_name: frontend
    
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped

    db:
      image: postgres:alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: postgres

    ngnix:
      image: nginx:alpine
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 80:80
      depends_on:
        - backend
        - frontend
      container_name: nginx